vim.g.neovide_cursor_vfx_mode = ''
vim.g.neovide_padding_top = 10
vim.g.neovide_padding_bottom = 0
vim.g.neovide_padding_right = 0
vim.g.neovide_padding_left = 0
vim.o.guifont = 'Hack Nerd Font:h15.5'
vim.g.neovide_scale_factor = 1.0
vim.opt.linespace = 5
vim.g.neovide_cursor_animation_length = 0
vim.g.neovide_hide_mouse_when_typing = true
vim.g.neovide_input_macos_alt_is_meta = true
